### ISSUE TITLE
some sound problem need help！

### ISSUE THREAD

**Issue by G31R6T** [Tang634724712/BomberKillers#3]
I added a sound def, but when I add g.sound（）, the sound cannot be played. Is this because of my computer or the sound playback path? please go to code check。

    def sound(self):
        pg.init()
        pg.mixer.init()
        pg.mixer.music.load(r"C:\Users\dell\BomberKillers\source\bk 1.mp3")
        pg.mixer.music.play(-1)

**Comment by Tang634724712** [comment]
could you please share the content of the terminal when running the program?

**Comment by Tang634724712** [comment]
The problem is you needn't write blablabla C:\Users....
The main.py is already in the source file, so you just write music.mp3.
Thak will work!

**Comment by G31R6T** [comment]
okokok. you said Yes.
